apiVersion: v1
kind: Service
metadata:
  name: ${NAME}
spec:
  selector:
    app: ${NAME}
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${NAME}
spec:
  selector:
    matchLabels:
      app: ${NAME}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${NAME}
    spec:
      containers:
        - name: ${NAME}
          image: ${REGISTRY}:${NAME}:${VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
