apiVersion: v1
kind: Service
metadata:
  name: ${name}
spec:
  selector:
    app: ${name}
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
spec:
  selector:
    matchLabels:
      app: ${name}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${name}
    spec:
      containers:
        - name: react-app
          image: ${registry}:${version}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
