pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = "${env.AWS_REGION}"

        eksClusterName = "${env.CLUSTER_NAME}"
        registry = "${env.ECR_URL}"
        registryCredential = "${env.AWS_CREDENTIAL_ID}"

        app_name = "backend"
        version = string(name: 'version', defaultValue: 'latest', description: 'Application Version')
    }

    stages {
        stage('Build') {
            steps {
                echo "Building ${app_name} image: ${registry}:${app_name}:${version}"
            }
        }

        stage('Deploy') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'user-aws',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {
                    sh '''
                        export APP_NAME="${app_name}";
                        export VERSION="${version}";
                        export REGISTRY="${registry}";
                        aws eks --region "${AWS_DEFAULT_REGION}" update-kubeconfig --name "${eksClusterName}"
                        kubectl apply -f ../mongodb.yaml
                        kubectl apply -f ../backend.yaml
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "Deployment successful"
        }
        failure {
            echo "Deployment failed"
        }
    }
}
